version: "2.4"

services:
  init-nginx:
    image: ${DOCKER_REGISTRY}/quoridor/nginx-certbot:latest
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - public-certs:/etc/nginx/certs
      - www-certbot:/var/www/certbot
      - ssl-dhparam:/etc/nginx/ssl
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:80" ]
      interval: 2s
      timeout: 3s
      retries: 5

  certbot:
    image: certbot/certbot:latest
    stdin_open: true
    tty: true
    command: >-
      certonly --manual --preferred-challenges=dns
      --email ${EMAIL} --agree-tos --no-eff-email
      -d quoridor.ru,*.quoridor.ru
    volumes:
      - public-certs:/etc/letsencrypt
      - www-certbot:/var/www/certbot
    depends_on:
      - init-nginx

  init-keys:
    image: ${DOCKER_REGISTRY}/quoridor/init-keys:latest
    build:
      dockerfile: jwt-keys.Dockerfile
    volumes:
      - jwt-keys:/var/keys

  init-tls:
    image: ${DOCKER_REGISTRY}/quoridor/init-tls:latest
    build:
      dockerfile: tls.Dockerfile
    volumes:
      - ssl-dhparam:/var/ssl
      - public-certs:/var/certs
    depends_on:
      - certbot

  init-game-api-tls:
    image: ${DOCKER_REGISTRY}/quoridor/init-game-api-tls:latest
    build:
      dockerfile: game-api-tls.Dockerfile
      args:
        SSL_KS_PASSWORD: ${SSL_KS_PASSWORD}
    volumes:
      - game-api-jks:/var/tmp/ks

volumes:
  public-certs:
    name: public-certs
  www-certbot:
    name: www-certbot
  jwt-keys:
    name: jwt-keys
  ssl-dhparam:
    name: ssl-dhparam
  game-api-jks:
    name: game-api-jks
