version: "3.8"

services:
  registry_certs:
    image: ${DOCKER_REGISTRY}/quoridor/registry-cert
    build: .
    volumes:
      - registry-certs:/var/certs

  registry:
    restart: always
    image: registry:2
    ports:
      - "5000:5000"
    environment:
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_TLS_CERTIFICATE: certs/registry.crt
      REGISTRY_HTTP_TLS_KEY: certs/registry.key
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_PATH: auth/htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
    volumes:
      - registry:/var/lib/registry
      - registry-auth:/auth
      - registry-certs:/certs
    depends_on:
      - registry_certs
      - registry_user

  registry_user:
    image: httpd:2
    entrypoint:
      - htpasswd
    command:
      -Bbc /auth/htpasswd ${DOCKER_REGISTRY_USERNAME} ${DOCKER_REGISTRY_PASSWORD}
    volumes:
      - registry-auth:/auth

volumes:
  registry:
    name: registry
  registry-auth:
    name: registry-auth
  registry-certs:
    name: registry-certs
