version: "3.8"

services:
  game-api-config:
    image: quoridor/game-api-config-local:latest
    volumes:
      - game-api-config:/conf

  game-api:
    image: quoridor/game-api:latest
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PSWD_PEPPER: ${PSWD_PEPPER}
      TS_PASSWORD: ${TS_PASSWORD}
    volumes:
      - game-api-config:/conf:ro
      - secret_keys:/var/keys
    depends_on:
      - game-api-config
      - migrations
      - token-store

  migrations:
    image: quoridor/migrations:latest
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: "jdbc:postgresql://db:5432/quoridor"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: quoridor
    volumes:
      - pgdata:/var/lib/postgresql/data

  token-store:
    image: redis:latest
    command: redis-server --requirepass ${TS_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/local/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - game-api
      - frontend

  frontend:
    image: quoridor/frontend:latest

volumes:
  game-api-config:
    name: game-api-config
  secret_keys:
    name: secret_keys
    external: true
  pgdata:
