version: "3"

services:
  quoridor-api:
    volumes:
      - ./keys:/var/keys:ro

  nginx:
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - frontend

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw

  frontend:
    image: node:lts-alpine
    working_dir: /home/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/build:/home/node/app
      - ./frontend/package.json:/home/node/package.json
    ports:
      - "3000:3000"
    command: "node app"
