version: "3"

services:
  quoridor-api-conf:
    build: .
    volumes:
      - ./configs:/conf:ro

  quoridor-api:
    build: ./target/docker/stage/
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      PSWD_PEPPER: ${PSWD_PEPPER}
      TS_PASSWORD: ${TS_PASSWORD}
    volumes:
      - ./configs:/conf:ro
    depends_on:
      - flyway
      - quoridor-api-conf
      - token-store

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://db:5432/quoridor -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: quoridor
    ports:
      - "5432:5432"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./static:/var/static
    depends_on:
      - quoridor-api

  token-store:
    image: redis:latest
    command: redis-server --requirepass ${TS_PASSWORD}
    restart: always
    ports:
      - "6379:6379"
