version: "2.4"

services:
  quoridor-api-conf:
    image: ${DOCKER_REGISTRY}/quoridor-config:latest
    volumes:
      - conf:/conf

  quoridor-api:
    image: ${DOCKER_REGISTRY}/quoridor-game:latest
    restart: on-failure:3
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      PSWD_PEPPER: ${PSWD_PEPPER}
      TS_PASSWORD: ${TS_PASSWORD}
    volumes:
      - conf:/conf:ro
    depends_on:
      - quoridor-api-conf
      - flyway
      - token-store

  flyway:
    image: flyway/flyway:latest
    restart: unless-stopped
    command: -url=jdbc:postgresql://db:5432/quoridor -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: quoridor
    volumes:
      - pgdata:/var/lib/postgresql/data

  token-store:
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${TS_PASSWORD}
    volumes:
      - rdata:/data

  nginx:
    image: ${DOCKER_REGISTRY}/quoridor-nginx:latest
    restart: on-failure:3
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - quoridor-api
      - frontend

  frontend:
    image: ${DOCKER_REGISTRY}/quoridor-frontend:latest
    restart: on-failure:3

volumes:
  conf:
  pgdata:
  rdata:
