version: "2.4"

services:
  game-api-conf:
    image: quoridor/game-api-config:latest
    volumes:
      - conf:/conf

  game-api:
    image: quoridor/game-api:latest
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      PSWD_PEPPER: ${PSWD_PEPPER}
      TS_PASSWORD: ${TS_PASSWORD}
    volumes:
      - conf:/conf:ro
    depends_on:
      - game-api-conf
      - flyway
      - token-store

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://db:5432/quoridor -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: quoridor
    volumes:
      - pgdata:/var/lib/postgresql/data

  token-store:
    image: redis:latest
    command: redis-server --requirepass ${TS_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/local/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - game-api
      - frontend

  frontend:
    image: quoridor/frontend:latest

volumes:
  conf:
  pgdata:
