version: "3"

services:
  quoridor-api-conf:
    build: .
    volumes:
      - ./configs:/conf:ro

  quoridor-api:
    build: ./target/docker/stage/
    restart: on-failure
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_USER: ${DB_USER}
      PSWD_PEPPER: ${PSWD_PEPPER}
      TS_PASSWORD: ${TS_PASSWORD}
    volumes:
      - ./configs:/conf:ro
    depends_on:
      - flyway
      - quoridor-api-conf
      - token-store

  flyway:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://db:5432/quoridor -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./migrations:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: quoridor
    ports:
      - "127.0.0.1:5432:5432"

  nginx:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - quoridor-api

  token-store:
    image: redis:latest
    command: redis-server --requirepass ${TS_PASSWORD}
    restart: always
    ports:
      - "127.0.0.1:6379:6379"

  frontend:
    image: node:lts-alpine
    working_dir: /home/node
    environment:
      - NODE_ENV=production
    volumes:
      - ./frontend/build:/home/node/app
      - ./frontend/package.json:/home/node/package.json
    ports:
      - "127.0.0.1:3000:3000"
    command: "node app"
