version: "3.8"

services:
  game-api-config:
    image: ${DOCKER_REGISTRY}/quoridor/game-api-config:latest
    pull_policy: always
    volumes:
      - game-api-config:/conf

  game-api:
    image: ${DOCKER_REGISTRY}/quoridor/game-api:latest
    pull_policy: always
    restart: on-failure:3
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PSWD_PEPPER: ${PSWD_PEPPER}
      TS_PASSWORD: ${TS_PASSWORD}
    volumes:
      - game-api-config:/conf:ro
      - secret_keys:/var/keys
      - game-api-jks:/var/game_certs
    depends_on:
      - game-api-config
      - migrations
      - token-store

  migrations:
    image: ${DOCKER_REGISTRY}/quoridor/migrations:latest
    pull_policy: always
    restart: on-failure:3
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: "jdbc:postgresql://db:5432/quoridor"
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: quoridor
    volumes:
      - pgdata:/var/lib/postgresql/data

  token-store:
    image: redis:latest
    restart: always
    command: redis-server --requirepass ${TS_PASSWORD}
    volumes:
      - rdata:/data

  nginx:
    image: ${DOCKER_REGISTRY}/quoridor/nginx:latest
    pull_policy: always
    restart: on-failure:3
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - tsl_certs:/etc/nginx/certs
      - ssl_dhparam:/etc/nginx/ssl
      - game-api-tls:/etc/nginx/game_certs
    depends_on:
      - game-api
      - frontend

  frontend:
    image: ${DOCKER_REGISTRY}/quoridor/frontend:latest
    pull_policy: always
    restart: on-failure:3

volumes:
  pgdata:
  rdata:
  game-api-config:
    name: game-api-config
  tsl_certs:
    name: tsl_certs
    external: true
  secret_keys:
    name: secret_keys
    external: true
  ssl_dhparam:
    name: ssl_dhparam
    external: true
  game-api-jks:
    name: game-api-jks
    external: true
  game-api-tls:
    name: game-api-tls
    external: true
