version: "3.8"

services:
  game-api-config:
    image: quoridor/game-api-config:local
    volumes:
      - game-api-config:/conf

  game-api:
    image: quoridor/game-api:latest
    deploy:
      replicas: 3
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      PSWD_PEPPER: ${PSWD_PEPPER}
      TS_PASSWORD: ${TS_PASSWORD}
      SSL_KS_PASSWORD: ${SSL_KS_PASSWORD}
    volumes:
      - game-api-config:/conf
      - jwt-keys:/var/keys
      - game-api-jks:/var/game-api-jks
    depends_on:
      - game-api-config
      - migrations
      - token-store

  migrations:
    image: quoridor/migrations:latest
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_URL: "jdbc:postgresql://db:5432/quoridor"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: quoridor
    volumes:
      - pgdata:/var/lib/postgresql/data

  token-store:
    image: redis:latest
    command: redis-server --requirepass ${TS_PASSWORD}

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/local/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/local/ssl-params.conf:/etc/nginx/ssl-params.conf
      - game-api-tls:/etc/nginx/game-api-tls
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - game-api
      - frontend

  frontend:
    image: quoridor/frontend:local

volumes:
  pgdata:
  game-api-config:
    name: game-api-config-${VERSION}
  jwt-keys:
    name: jwt-keys
    external: true
  game-api-jks:
    name: game-api-jks
    external: true
  game-api-tls:
    name: game-api-tls
    external: true
