version: "3.8"

services:
  migrations:
    image: flyway/flyway:latest
    command: -url=jdbc:postgresql://db:5432/quoridor -user=${DB_USER} -password=${DB_PASSWORD} -connectRetries=60 migrate
    volumes:
      - ./migrations/sql:/flyway/sql
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: quoridor
    volumes:
      - pgdata_dev:/var/lib/postgresql/data

  token-store:
    image: redis:latest
    command: redis-server --requirepass ${TS_PASSWORD}
    ports:
      - "6379:6379"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    network_mode: host
    volumes:
      - ./nginx/dev/nginx.conf:/etc/nginx/nginx.conf

volumes:
  pgdata_dev:
