version: "2.4"

services:
  init-nginx:
    build:
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - tsl_certs:/etc/nginx/certs
      - www_certbot:/var/www/certbot
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:80" ]
      interval: 2s
      timeout: 3s
      retries: 5

  certbot:
    image: certbot/certbot:latest
    command: >-
      certonly --webroot --webroot-path=/var/www/certbot
      --email ${EMAIL} --agree-tos --no-eff-email
      -d quoridor.online,www.quoridor.online
    volumes:
      - tsl_certs:/etc/letsencrypt
      - www_certbot:/var/www/certbot
    depends_on:
      - init-nginx

  init-keys:
    build:
      dockerfile: jwt-keys.Dockerfile
    volumes:
      - secret_keys:/var/keys

  init-tls:
    build:
      dockerfile: tls.Dockerfile
    volumes:
      - ssl_dhparam:/var/ssl
      - tsl_certs:/var/certs
    depends_on:
      - certbot

  init-game-api-tls:
    build:
      dockerfile: game-api-tls.Dockerfile
      args:
        STOREPASS: ${STOREPASS}
    volumes:
      - game-api-jks:/var/tmp/ks
      - game-api-tls:/var/tmp/cert

volumes:
  tsl_certs:
    name: tsl_certs
  www_certbot:
    name: www_certbot
  secret_keys:
    name: secret_keys
  ssl_dhparam:
    name: ssl_dhparam
  game-api-jks:
    name: game-api-jks
  game-api-tls:
    name: game-api-tls
