version: "2.4"

services:
  init-nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./sample/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/letsencrypt:/etc/nginx/ssl:ro
      - ./certbot/www:/var/www/certbot:ro
    healthcheck:
      test: [ "CMD", "curl", "http://localhost:80" ]
      interval: 2s
      timeout: 3s
      retries: 5

  certbot:
    image: certbot/certbot:latest
    command: >-
      certonly --webroot --webroot-path=/var/www/certbot
      --email ${EMAIL} --agree-tos --no-eff-email
      -d quoridor.online,www.quoridor.online
    volumes:
      - ./certbot/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - init-nginx
