name: Deployment

on:
  workflow_dispatch

permissions:
  contents: read

env:
  HD: ${{ vars.HD }}

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'sbt'
    - run: mkdir "$HOME/.ssh"
    - run: echo "${{ secrets.ID_ED25519 }}" > "$HOME/.ssh/id_ed25519"
    - run: chmod 600 "$HOME/.ssh/id_ed25519"
    - run: sbt "Docker / stage"
    - run: ssh -i "$HOME/.ssh/id_ed25519" -o StrictHostKeyChecking=no
           aliakovl@quoridor.online "cd $HD && docker-compose down" || true
    - run: rsync -a -z --delete-after
           ./migrations ./nginx ./target ./static ./configs
           ./docker-compose.yml ./docker-compose.prod.yml
           ./Dockerfile ./Makefile "aliakovl@quoridor.online:$HD"
    - run: ssh aliakovl@quoridor.online
           'bash -c "cd $HD &&\
            export DB_USER=${{ vars.DB_USER }} &&\
            export DB_PASSWORD=${{ secrets.DB_PASSWORD }} &&\
            make prod"'
